bookers/config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  resources :books
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord

  validates:title, presence:true
  validates:body, presence:true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
   @book = Book.new(book_params)
   if @book.save
     flash[:notice] = "Book was successfully created."  #message
     redirect_to book_path(@book.id)
   else
     @books = Book.all
     render:index;
   end
  end



  def index
    @book=Book.new
    @books=Book.all
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
   if @book.save
     flash[:notice] = "Book was successfully updated."
     redirect_to book_path(@book.id)
   else
     @books = Book.all
     flash[:notice] ="error! update failed."
     render:edit;
   end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%=@book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

    <h4>Titleル</h4>
  <%= f.text_field:title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
  <p><%= link_to "show", book_path(@book.id) %>|<%= link_to "back", books_url %></p>

<% end %>

bookers/app/views/books/index.html.erb
<h1>Books</h1>


<div class="indextitle">
<p>Title</p>
<% @books.each do |book| %>
<p>
<%=  book.title %><% end %></p>
</div>


<div class="indexbody"><p>Body</p>
 <% @books.each do |book| %>
 <p  ><%= book.body %><% end %>
</p></div>

 <div class="kick"> <% @books.each do |book| %>
 <p><%= link_to "Show", book_path(book.id) %>
 <%= link_to "Edit", edit_book_path(book.id) %>
 <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
 <% end %>
 </p>
 </div>





<h1>New book</h1>
<% if @book.errors.any? %>
  <%=@book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


    <%= form_with model: @book, url:'/books', method: :post do |f| %>
    <h4 >Title</h4>
    <%= f.text_field :title %>

    <h4>Body文</h4>
    <div class="table"><%= f.text_area :body%></div>


    <div class="table"><%=  f.submit 'Create Book' %></div>


  <% end %>

bookers/app/views/books/new.html.erb
<h1>Books</h1>

<% @books.each do |list| %>

 <p>Title<%= @book.title %>body<%= @book.body %>


 </p>

<% end %>



<h1>New book</h1>
<% if @book.errors.any? %>
  <%=@book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


    <%= form_with model: @book, url:'/books', method: :post do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body文</h4>
    <%= f.text_area :body %>
    <rb>

    <%= f.submit 'Create Book' %>


  <% end %>

bookers/app/views/books/show.html.erb
<p><strong>title:</strong><%= @book.title %></p>

<p><strong>body:</strong><%= @book.body %></p>


<p><%= link_to "edit", edit_book_path(@book.id) %>|<%= link_to "back", books_url %></p>

bookers/app/views/homes/top.html.erb
<head>
  <link rel="stylesheet" href="home.css">
</head>

<body>
<h1>
  "ようこそ"
    <strong>Bookers</strong>
  "へ！"
</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>

<%= link_to "start", "/books" %>
</body>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <% if flash[:notice] %>
    <div class="flash">
         <%= flash[:notice] %>
    </div>
<% end %>
  </header>
  <body>
    <%= yield %>
  </body>
</html>